// Code generated by protoc-gen-go.
// source: mallhome.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	mallhome.proto

It has these top-level messages:
	MallHomeReq
	MallHome
	HotGoods
	UserInfo
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MallHomeReq struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *MallHomeReq) Reset()                    { *m = MallHomeReq{} }
func (m *MallHomeReq) String() string            { return proto.CompactTextString(m) }
func (*MallHomeReq) ProtoMessage()               {}
func (*MallHomeReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MallHomeReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type MallHome struct {
	UserInfo *UserInfo `protobuf:"bytes,1,opt,name=userInfo" json:"userInfo,omitempty"`
	HotGoods *HotGoods `protobuf:"bytes,2,opt,name=hotGoods" json:"hotGoods,omitempty"`
}

func (m *MallHome) Reset()                    { *m = MallHome{} }
func (m *MallHome) String() string            { return proto.CompactTextString(m) }
func (*MallHome) ProtoMessage()               {}
func (*MallHome) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MallHome) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func (m *MallHome) GetHotGoods() *HotGoods {
	if m != nil {
		return m.HotGoods
	}
	return nil
}

type HotGoods struct {
	GoodsId   string `protobuf:"bytes,1,opt,name=goods_id,json=goodsId" json:"goods_id,omitempty"`
	GoodsName string `protobuf:"bytes,2,opt,name=goods_name,json=goodsName" json:"goods_name,omitempty"`
	Describe  string `protobuf:"bytes,3,opt,name=describe" json:"describe,omitempty"`
	Price     string `protobuf:"bytes,4,opt,name=price" json:"price,omitempty"`
	Factory   string `protobuf:"bytes,5,opt,name=factory" json:"factory,omitempty"`
}

func (m *HotGoods) Reset()                    { *m = HotGoods{} }
func (m *HotGoods) String() string            { return proto.CompactTextString(m) }
func (*HotGoods) ProtoMessage()               {}
func (*HotGoods) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *HotGoods) GetGoodsId() string {
	if m != nil {
		return m.GoodsId
	}
	return ""
}

func (m *HotGoods) GetGoodsName() string {
	if m != nil {
		return m.GoodsName
	}
	return ""
}

func (m *HotGoods) GetDescribe() string {
	if m != nil {
		return m.Describe
	}
	return ""
}

func (m *HotGoods) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *HotGoods) GetFactory() string {
	if m != nil {
		return m.Factory
	}
	return ""
}

type UserInfo struct {
	UserIds  string `protobuf:"bytes,1,opt,name=user_ids,json=userIds" json:"user_ids,omitempty"`
	UserName string `protobuf:"bytes,2,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	UserTag  string `protobuf:"bytes,3,opt,name=user_tag,json=userTag" json:"user_tag,omitempty"`
	Sex      string `protobuf:"bytes,4,opt,name=sex" json:"sex,omitempty"`
	Phone    string `protobuf:"bytes,5,opt,name=phone" json:"phone,omitempty"`
	Email    string `protobuf:"bytes,6,opt,name=email" json:"email,omitempty"`
}

func (m *UserInfo) Reset()                    { *m = UserInfo{} }
func (m *UserInfo) String() string            { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()               {}
func (*UserInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UserInfo) GetUserIds() string {
	if m != nil {
		return m.UserIds
	}
	return ""
}

func (m *UserInfo) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserInfo) GetUserTag() string {
	if m != nil {
		return m.UserTag
	}
	return ""
}

func (m *UserInfo) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *UserInfo) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterType((*MallHomeReq)(nil), "pb.MallHomeReq")
	proto.RegisterType((*MallHome)(nil), "pb.MallHome")
	proto.RegisterType((*HotGoods)(nil), "pb.HotGoods")
	proto.RegisterType((*UserInfo)(nil), "pb.UserInfo")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GetMallHome service

type GetMallHomeClient interface {
	GetMallHome(ctx context.Context, in *MallHomeReq, opts ...grpc.CallOption) (*MallHome, error)
}

type getMallHomeClient struct {
	cc *grpc.ClientConn
}

func NewGetMallHomeClient(cc *grpc.ClientConn) GetMallHomeClient {
	return &getMallHomeClient{cc}
}

func (c *getMallHomeClient) GetMallHome(ctx context.Context, in *MallHomeReq, opts ...grpc.CallOption) (*MallHome, error) {
	out := new(MallHome)
	err := grpc.Invoke(ctx, "/pb.GetMallHome/GetMallHome", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GetMallHome service

type GetMallHomeServer interface {
	GetMallHome(context.Context, *MallHomeReq) (*MallHome, error)
}

func RegisterGetMallHomeServer(s *grpc.Server, srv GetMallHomeServer) {
	s.RegisterService(&_GetMallHome_serviceDesc, srv)
}

func _GetMallHome_GetMallHome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MallHomeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetMallHomeServer).GetMallHome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GetMallHome/GetMallHome",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetMallHomeServer).GetMallHome(ctx, req.(*MallHomeReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _GetMallHome_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.GetMallHome",
	HandlerType: (*GetMallHomeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMallHome",
			Handler:    _GetMallHome_GetMallHome_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mallhome.proto",
}

func init() { proto.RegisterFile("mallhome.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0xcf, 0x4f, 0x83, 0x30,
	0x14, 0xc7, 0x65, 0x73, 0x5b, 0x79, 0x5b, 0xd4, 0x34, 0x26, 0xd6, 0x19, 0x13, 0xc3, 0xc1, 0xec,
	0xc4, 0x61, 0x9e, 0x3d, 0x6f, 0x3b, 0xe8, 0x81, 0xe8, 0x55, 0x53, 0xc6, 0xdb, 0x46, 0x42, 0x29,
	0x52, 0x4c, 0xf4, 0xbf, 0xf0, 0xee, 0x3f, 0x6b, 0xfa, 0x5a, 0x18, 0xde, 0xfa, 0xfd, 0x51, 0xf8,
	0xf0, 0x1e, 0x70, 0xa6, 0x64, 0x51, 0x1c, 0xb4, 0xc2, 0xb8, 0xaa, 0x75, 0xa3, 0xf9, 0xa0, 0x4a,
	0xa3, 0x7b, 0x98, 0x3e, 0xc9, 0xa2, 0x58, 0x6b, 0x85, 0x09, 0x7e, 0xf0, 0x2b, 0x98, 0x7c, 0x1a,
	0xac, 0xdf, 0xf3, 0x4c, 0x04, 0x77, 0xc1, 0x22, 0x4c, 0xc6, 0x56, 0x6e, 0xb2, 0xe8, 0x0d, 0x58,
	0xdb, 0xe3, 0x0b, 0x60, 0xe4, 0x96, 0x3b, 0x4d, 0xad, 0xe9, 0x72, 0x16, 0x57, 0x69, 0xfc, 0xea,
	0xbd, 0xa4, 0x4b, 0x6d, 0xf3, 0xa0, 0x9b, 0x95, 0xd6, 0x99, 0x11, 0x83, 0x63, 0x73, 0xed, 0xbd,
	0xa4, 0x4b, 0xa3, 0x9f, 0x00, 0x58, 0x6b, 0xf3, 0x6b, 0x60, 0x7b, 0x7b, 0x38, 0x62, 0x4c, 0x48,
	0x6f, 0x32, 0x7e, 0x0b, 0xe0, 0xa2, 0x52, 0x2a, 0xa4, 0x67, 0x86, 0x49, 0x48, 0xce, 0xb3, 0x54,
	0xc8, 0xe7, 0xc0, 0x32, 0x34, 0xdb, 0x3a, 0x4f, 0x51, 0x0c, 0x29, 0xec, 0x34, 0xbf, 0x84, 0x51,
	0x55, 0xe7, 0x5b, 0x14, 0xa7, 0x14, 0x38, 0xc1, 0x05, 0x4c, 0x76, 0x72, 0xdb, 0xe8, 0xfa, 0x5b,
	0x8c, 0xdc, 0xab, 0xbc, 0x8c, 0x7e, 0x03, 0x60, 0xed, 0x37, 0x59, 0x24, 0x3f, 0x18, 0xd3, 0x22,
	0xb9, 0xc9, 0x18, 0x7e, 0x03, 0x21, 0x45, 0x3d, 0x22, 0xea, 0x12, 0x50, 0x7b, 0xaf, 0x91, 0x7b,
	0x0f, 0x44, 0xf7, 0x5e, 0xe4, 0x9e, 0x5f, 0xc0, 0xd0, 0xe0, 0x97, 0xa7, 0xb1, 0x47, 0x22, 0x3c,
	0xe8, 0x12, 0x3d, 0x89, 0x13, 0xd6, 0x45, 0x25, 0xf3, 0x42, 0x8c, 0x9d, 0x4b, 0x62, 0xf9, 0x08,
	0xd3, 0x15, 0x36, 0xdd, 0x4e, 0xe2, 0xff, 0xf2, 0xdc, 0x8e, 0xb9, 0xb7, 0xd8, 0xf9, 0xac, 0x6f,
	0x44, 0x27, 0xe9, 0x98, 0x7e, 0x81, 0x87, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x78, 0x73, 0x5f,
	0x5c, 0x14, 0x02, 0x00, 0x00,
}
